"""empty message

Revision ID: 1f8f08d3286
Revises: 420611fd93
Create Date: 2015-11-14 23:34:21.950054

"""

# revision identifiers, used by Alembic.
revision = '1f8f08d3286'
down_revision = '420611fd93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

indicator_helper = sa.Table('indicators',
                            sa.MetaData(),
                            sa.Column('id'),
                            sa.Column('fcf'),
                            )


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    for indicator in connection.execute(indicator_helper.select()):
        fcf = indicator.fcf

        #if fcf is not None:
        #    if fcf[-1] == "B":
        #        fcf_cleaned = float(fcf[:-1]) * 1000000000.0
        #    elif fcf[-1] == "M":
        #        fcf_cleaned = float(fcf[:-1]) * 1000000.0
        #    elif fcf[-1] == "K":
        #        fcf_cleaned = float(fcf[:-1]) * 1000.0
        #    else:
        #        try:
        #            fcf_cleaned = float(fcf)
        #        except ValueError:
        #            fcf_cleaned = None
        #else:
        #    fcf_cleaned = "NULL"
        #    connection.execute(
        #        indicator_helper.update().where(
        #                                        indicator_helper.c.id==indicator.id
        #                                        ).values(
        #                                                 fcf=fcf_cleaned
        #                                                 )
        #                   )
    op.alter_column('indicators', 'fcf',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'fcf',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('indicators', 'blah')
    ### end Alembic commands ###
