"""empty message

Revision ID: 420611fd93
Revises: 
Create Date: 2015-11-13 23:45:09.948981

"""

# revision identifiers, used by Alembic.
revision = '420611fd93'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker


def upgrade():
    #from sqlalchemy.ext.serializer import loads
    #from sqlalchemy import Metadata
    #connection = op.get_bind()
    ##for idx,company in enumerate(connection.execute("select * from company")):
    #    #print(idx, company)
    ## commands auto generated by Alembic - please adjust! ###
    #op.create_table('company',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('symbol', sa.String(length=50), nullable=False),
    #sa.Column('name', sa.String(length=50), nullable=True),
    #sa.Column('sector', sa.String(length=50), nullable=True),
    #sa.Column('industry', sa.String(length=50), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('name'),
    #sa.UniqueConstraint('symbol')
    #)
    #op.create_table('indicators',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('date', sa.Date(), nullable=True),
    #sa.Column('buy', sa.Boolean(), nullable=True),
    #sa.Column('roe', sa.Float(), nullable=True),
    #sa.Column('fcf', sa.String(), nullable=True),
    #sa.Column('pm', sa.Float(), nullable=True),
    #sa.Column('om', sa.Float(), nullable=True),
    #sa.Column('tde', sa.Float(), nullable=True),
    #sa.Column('pe', sa.Float(), nullable=True),
    #sa.Column('cr', sa.Float(), nullable=True),
    #sa.Column('peg', sa.Float(), nullable=True),
    #sa.Column('eps', sa.Float(), nullable=True),
    #sa.Column('div', sa.Float(), nullable=True),
    #sa.Column('pfy', sa.Float(), nullable=True),
    #sa.Column('nfy', sa.Float(), nullable=True),
    #sa.Column('cp', sa.Float(), nullable=True),
    #sa.Column('fp', sa.Float(), nullable=True),
    #sa.Column('b15', sa.Float(), nullable=True),
    #sa.Column('b12', sa.Float(), nullable=True),
    #sa.Column('company_id', sa.Integer(), nullable=True),
    #sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
    ### end Alembic commands ###
    pass

def downgrade():
    #from stocks.db.models import Company, Indicators
    #from sqlalchemy.ext.serializer import dumps
    #connection = op.get_bind()
    #indicators = connection.execute("select * from indicators")
    #company = connection.execute("select * from company")
    #serial_i = dumps(indicators.fetchall())
    #serial_c = dumps(company.fetchall())
    #write_table("indicators.tbl", serial_i)
    #write_table("company.tbl", serial_c)
    #op.drop_table('indicators')
    #op.drop_table('company')
    ### end Alembic commands ###
    pass

def write_table(filename, obj):
    f = open(filename, "wb")
    f.write(obj)
    f.close
